export const SS = '_SUCCESS';
export const ER = '_ERROR';

export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';
export const AUTH_SIGN_UP_CONFIRM = 'AUTH_SIGN_UP_CONFIRM';
export const AUTH_USER_INFO = 'AUTH_USER_INFO';
export const AUTH_CHECK_USER = 'AUTH_CHECK_USER';
export const AUTH_RESEND_CODE = 'AUTH_RESEND_CODE';

export const LIST_USERS = 'LIST_USERS';

export const GET_USER_API = 'GET_USER_API';
export const CREATE_USER_API = 'CREATE_USER_API';

export const ITEMS = 'ITEMS';
export const ADD_ITEM = 'ADD_ITEM';

export const LIST_CATEGORY = 'LIST_CATEGORY';
export const LIST_CATEGORY_SUCCESS = 'LIST_CATEGORY_SUCCESS';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const LIST_PRODUCT = 'LIST_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY';
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS =
  'GET_PRODUCTS_BY_CATEGORY_SUCCESS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const UDPATE_CART_QUANTITY = 'UDPATE_CART_QUANTITY';
export const CLEAR_CART = 'CLEAR_CART';

export const CREATE_ORDER = 'CREATE_ORDER';
export const LIST_ORDERS = 'LIST_ORDERS';
